### ISSUE TITLE
Session Milky Stout au caramel salé de Bretagne

### ISSUE THREAD

**Issue by valeriangalliat** [valeriangalliat/sans-pression#19]
Mix of:

Caramel malt 120L: https://www.ontariobeerkegs.com/Caramel_Malt_Crystal_120L_1_lb_Crushed_p/malt-crushed-crystal120.htm
Chocolate wheat: https://www.ontariobeerkegs.com/Chocolate_Wheat_Weyermann_1_lb_Crushed_p/malt-crushed-chocolatewheat.htm
Pale chocolate malt: https://www.ontariobeerkegs.com/Pale_Chocolate_Malt_1_lb_Crushed_p/malt-crushed-palechocolate.htm

Would probably do most of caramel malt, like 8 lb of caramel, 1 lb of chocolate wheat and 1 or 2 lb of pale chocoalte malt

Some oats too: https://www.ontariobeerkegs.com/Flaked_Oats_OiO_1_lb_p/malt-1lb-flaked-oats.htm

Looks like it would be good with Williamette hops: https://www.ontariobeerkegs.com/US_Willamette_Hop_Pellets_1_oz_p/hops-willamette.htm

And Challenger: https://www.ontariobeerkegs.com/UK_Challenger_Hop_Pellets_1_oz_p/hops-challenger.htm

Something like 1 oz each

Try farmhouse yeast to make it a farmhouse milk stout? https://www.ontariobeerkegs.com/Omega_Yeast_Jovaru_Lithuanian_Farmhouse_Ale_Yeast_p/oyl033-jovaru-lithuanian-farmh.htm

**Comment by valeriangalliat** [comment]
dump de l'extrait de vanille a l'embouteillage, ou fermenter avec vanille, ou DH vanille?

**Comment by valeriangalliat** [comment]
"Before we go into each caramel malt, you need to know that Caramel and Crystal malts have no diastatic power, so they are to be used as an adjunct and never a base malt. Generally caramel makes up 2-15% of the grist, but in some cases may be slightly higher." gonna need to revisit that recipe

**Comment by valeriangalliat** [comment]
Not too much pale as well "Some brewers get gun shy about roasted malts, but fear not. Roasted malts are delicious, provided you don't go completely overboard: 10% (or roughly one pound in an average-gravity 5 gallon batch) is about the most you would usually use. Stay below this amount and it's hard to go wrong. "

**Comment by valeriangalliat** [comment]
More likely most munich malt https://www.ontariobeerkegs.com/Munich_Malt_I_Weyermann_1_lb_Crushed_p/malt-crushed-munich-i.htm and keep chocolate/caramel for smaller touches

**Comment by mewfree** [comment]
https://thefoodxp.com/milk-stout-recipe/

**Comment by valeriangalliat** [comment]
For botteling look at https://www.homebrewtalk.com/threads/how-much-vanilla-extract-for-5-gallons.258222/

**Comment by valeriangalliat** [comment]
https://thefoodxp.com/milk-stout-recipe/
